
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtsekxjhqvwnpexnszwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0c2VreGpocXZ3bnBleG5zendsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MjQ5MTcsImV4cCI6MjA2MjMwMDkxN30.uWQzbwKKnIEftK-zfVPUvVoOa6RDaQBL8PCM4EGdQz0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
